"""Initial migration.

Revision ID: 0b9bb7ba8f44
Revises: 
Create Date: 2023-07-06 09:36:18.056125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9bb7ba8f44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('_hashed_password', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('volume_basement', sa.Integer(), nullable=True),
    sa.Column('overall_qual', sa.Integer(), nullable=True),
    sa.Column('allbath_grd', sa.Float(), nullable=True),
    sa.Column('mssubclass', sa.Integer(), nullable=True),
    sa.Column('neighborhood', sa.String(), nullable=True),
    sa.Column('garagearea', sa.Integer(), nullable=True),
    sa.Column('bsmtfinsf1', sa.Integer(), nullable=True),
    sa.Column('year_remod_add', sa.Integer(), nullable=True),
    sa.Column('kitchen_qual', sa.Integer(), nullable=True),
    sa.Column('sale_condition', sa.String(), nullable=True),
    sa.Column('prediction', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction')
    op.drop_table('user')
    # ### end Alembic commands ###
