"""Changement de nom de colonne

Revision ID: 39ff19c5433f
Revises: 0b9bb7ba8f44
Create Date: 2023-07-06 10:18:03.730909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39ff19c5433f'
down_revision = '0b9bb7ba8f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volumebasement', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('overallqual', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('allbathgrd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('yearremodadd', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kitchenqual', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('salecondition', sa.String(), nullable=True))
        batch_op.drop_column('overall_qual')
        batch_op.drop_column('allbath_grd')
        batch_op.drop_column('kitchen_qual')
        batch_op.drop_column('year_remod_add')
        batch_op.drop_column('sale_condition')
        batch_op.drop_column('volume_basement')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('volume_basement', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('sale_condition', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('year_remod_add', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('kitchen_qual', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('allbath_grd', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('overall_qual', sa.INTEGER(), nullable=True))
        batch_op.drop_column('salecondition')
        batch_op.drop_column('kitchenqual')
        batch_op.drop_column('yearremodadd')
        batch_op.drop_column('allbathgrd')
        batch_op.drop_column('overallqual')
        batch_op.drop_column('volumebasement')

    # ### end Alembic commands ###
