"""Changement de nom de colonnes pour revenir aux noms des colonnes d'entraînement

Revision ID: e07399e76b7a
Revises: 39ff19c5433f
Create Date: 2023-07-06 10:30:53.042505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e07399e76b7a'
down_revision = '39ff19c5433f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('VolumeBasement', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('OverallQual', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('AllBathGrd', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('MSSubClass', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('Neighborhood', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('GarageArea', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('BsmtFinSF1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('YearRemod__Add', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('KitchenQual', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('SaleCondition', sa.String(), nullable=True))
        batch_op.drop_column('overallqual')
        batch_op.drop_column('volumebasement')
        batch_op.drop_column('allbathgrd')
        batch_op.drop_column('neighborhood')
        batch_op.drop_column('kitchenqual')
        batch_op.drop_column('mssubclass')
        batch_op.drop_column('garagearea')
        batch_op.drop_column('bsmtfinsf1')
        batch_op.drop_column('salecondition')
        batch_op.drop_column('yearremodadd')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('yearremodadd', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('salecondition', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('bsmtfinsf1', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('garagearea', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('mssubclass', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('kitchenqual', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('neighborhood', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('allbathgrd', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('volumebasement', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('overallqual', sa.INTEGER(), nullable=True))
        batch_op.drop_column('SaleCondition')
        batch_op.drop_column('KitchenQual')
        batch_op.drop_column('YearRemod__Add')
        batch_op.drop_column('BsmtFinSF1')
        batch_op.drop_column('GarageArea')
        batch_op.drop_column('Neighborhood')
        batch_op.drop_column('MSSubClass')
        batch_op.drop_column('AllBathGrd')
        batch_op.drop_column('OverallQual')
        batch_op.drop_column('VolumeBasement')

    # ### end Alembic commands ###
